WebApplication/HabiWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

WebApplication/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    # # ex: /polls/
    # path('', views.index, name='index'),

    path('', views.IndexView.as_view(), name='index'),
    path('test/', views.test, name='test'),
    path('send/',views.send, name='send'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),

    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

WebApplication/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from Deep_Learning.Neural_Network import main as cnn


# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class ConvNeuralNetwork(models.Model):
    train_class = cnn.load_instance('train_class')

    def __str__(self):
        return 'test_ver 1.0'

WebApplication/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.template import loader
from .models import Choice, Question, ConvNeuralNetwork
import numpy as np
import json

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # template = loader.get_template('polls/index.html')
#     # context = {
#     #     'latest_question_list': latest_question_list,
#     # }
#     # return HttpResponse(template.render(context, request))
#     ### 템플릿에 context를 채워넣어 표현한 결과를 HttpRespose와 같이 반환하는 형태를 단축 기능을 통해 사용가능
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)

def test(request):
    # idx = 5
    # ConvNeuralNetwork.train_class.predict(idx)
    return render(request, 'polls/test.html', {})


def send(request):
    print('send@@@@@@@@@@')
    arr = json.loads(request.POST['image'])
    np_arr = np.array(arr)
    np_arr = np_arr.astype(np.float32)
    np_arr /= 255.0
    np_arr = np_arr.reshape(1,1,28,28)
    ConvNeuralNetwork.train_class.predict(np_arr)
    context = {
        'status' : 'success'
    }
    return HttpResponse(json.dumps(context), content_type="application/json")


# def detail(request, question_id):
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     # return render(request, 'polls/detail.html', {'question': question})
#     ### 단축 기능 get_object_or_404
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

WebApplication/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

WebApplication/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id  %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

WebApplication/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

WebApplication/polls/templates/polls/test.html
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function(){
         // document.body.style.backgroundColor = "red";
         var DrawingTool = {
            canvas   : null,
            context  : null,
            drawX    : [],
            drawY    : [],
            drawDrag : [],
            drawColor: [],
            isDraw   : false,
            colorTable : [
                "#000000",
                "#ff0000",
                "#0000ff",
                "#ffff00",
                "#cb3594",
                "#986828"
            ]
        };

            DrawingTool.init = function() {
                var self = this;
                var offset = $("#canvas").offset();
                this.canvas = document.getElementById("canvas");
                this.context = this.canvas.getContext("2d");

                $("#canvas").mousedown(function(event) {
                    self.isDraw = true;
                    self.addDraw(event.pageX - offset.left, event.pageY - offset.top);
                    self.reDraw();
                });

                $("#canvas").mousemove(function(event) {
                    if(self.isDraw) {
                        self.addDraw(event.pageX - offset.left, event.pageY - offset.top, true);
                        self.reDraw();
                    }
                });

                $("#canvas").bind("mouseup mouseleave", function(event) {
                    self.isDraw = false;
                });

                this.setColorButton();
                this.setResetButton();
            };

            DrawingTool.addDraw = function(x, y, drawing) {
                this.drawX.push(x);
                this.drawY.push(y);
                this.drawDrag.push(drawing);
                this.drawColor.push(this.selectedColor || this.colorTable[0]);
            };

            DrawingTool.reDraw = function() {
                this.context.lineJoin = "round";
                this.context.lineWidth = 11;

                for(var i = 0; i < this.drawX.length; i ++) {
                    this.context.beginPath();
                    if(this.drawDrag[i] && i) {
                        this.context.moveTo(this.drawX[i - 1], this.drawY[i - 1]);
                    } else {
                        this.context.moveTo(this.drawX[i] - 1, this.drawY[i]);
                    }

                    this.context.lineTo(this.drawX[i], this.drawY[i]);
                    this.context.closePath();
                    this.context.strokeStyle = this.drawColor[i];
                    this.context.stroke();
                }
            };

            DrawingTool.setColorButton = function() {
                var self = this;
                $("#color > button").on("click", function(event) {
                    self.selectedColor = self.colorTable[$(this).index()];
                });
            };

            DrawingTool.setResetButton = function() {
                var self = this;
                $("#reset").on("click", function(event) {
                    self.canvas.width = self.canvas.width;
                    self.drawX = [], self.drawY = [], self.drawDrag = [], self.drawColor = [];
                });
            };


        DrawingTool.init();

        $('#send').click(function(){
            var img = new Image();
            img.onload = function() {
                var re_canvas = document.createElement('canvas');
                var re_context = re_canvas.getContext("2d");
                re_canvas.width = img.width;
                re_canvas.height = img.height;
                re_context.drawImage(img, 0,0, img.width, img.height, 0,0, 28, 28);
                sendData(re_context);
            }
            img.src = DrawingTool.canvas.toDataURL('image/png', 1.0);
        });
        });
        var sendData = function(re_context) {
            var imgArr = re_context.getImageData(0,0,28,28).data;
            var red = [];
            var green = [];
            var blue = [];
            var alpha = [];
            for(var i=0; i<imgArr.length; i+=4){
                red.push(imgArr[i+0])
                green.push(imgArr[i+1])
                blue.push(imgArr[i+2])
                alpha.push(imgArr[i+3])
            }
            $.ajax({
                type: "POST",
                url: "{% url 'polls:send' %}",
                data: {'image': JSON.stringify(alpha),'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: "json"
                }).done(function(data){
                console.info(data.status)
            });
        }
    </script>
</head>

<div id="tools">
    <p>
        <button id="reset">RESET</button>
        <button id="send">SEND</button>
    </p>
    <p id="color">
        <button>BLACK</button>
        <button>RED</button>
        <button>BLUE</button>
        <button>YELLOW</button>
        <button>PURPLE</button>
        <button>BROWN</button>
    </p>
</div>
<canvas id="canvas" width="300" height="300"></canvas>

<style>
    #canvas { border: 1px solid #000; }
</style>